# Generated by Django 5.1.1 on 2024-09-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='order_type',
            field=models.CharField(choices=[('Market', 'Market'), ('Limit', 'Limit'), ('Stop', 'Stop')], default='Market', max_length=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
